vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       gamesPictures:
           uri_prefix: /images/gamesPictures
           upload_destination: '%kernel.project_dir%/public/images/gamesPictures'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
